---
title: 'R: Tutorial & Collection of Useful Commands'
subtitle: '(for applications in economics)'
author: "Marko Mlikota, https://markomlikota.github.io"
output:
  html_document: 
    fig_width: 6
    fig_height: 3.75
    fig_caption: true
    highlight: zenburn
    toc: false
    toc_depth: 1
    toc_float: true
    number_sections: false
    css: style.css
  pdf_document:
    fig_width: 6
    fig_height: 3.75
    fig_caption: true
    highlight: zenburn
---


<style type="text/css">
body, td {
   font-size: 18px;
}
code.r{
  font-size: 16px;
}
pre {
  font-size: 16px
}
h1 {
  font-size: 35px;
  margin: 60px 0px 30px 0px;
}
h2 {
  font-size: 25px;
}
#TOC {
  color: black; 
}

</style>

<script>
  var height=$('#primary').height(); // Calculate primary wrapper height
  $('#secondary').height(height); // Set the height it to sidebar
</script>




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(results=TRUE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(tidy=TRUE)
knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
#knitr::opts_chunk$set(fig.width=5, fig.height=3)
```


# General Coding Advice


* Before you start coding, be clear on what you want to achieve and how to go about it (roughly).
* It is good practice to include at the top of your code: 
	+ a header with: your name, contact information (email/website), the purpose of the code (title and a short description)
	+ an introductory code that i) deletes everything in the environment and console, ii) loads all packages used in script, and iii) defines all paths
* Clearly mark the different parts of your script, using comments, lines, spaces to create sections, subsections, etc. 
* Adopt a naming convention, e.g.
	+ use the so-called lowerCamelCase
	+ start binary variables with "is" or "include" or other verb (e.g. isUtilityPositive or includeLimits)
	+ start functions with f (e.g. fCombineStrings)
	+ start object-names with v, a, m, i for vector, array, matrix, iterator, string (and combine, if necessary; e.g. vsVars is vector of strings
* Divide program into (many small) functions. This is easier to reuse, to test, and it (often) runs faster.
* For standard problems (e.g. interpolation, kernel density estimation, etc.), before you do it yourself, see whether there is a library that does it.
* For bigger projects, use Git to keep track of version changes.	
* Think about optimization only once the code runs. And ask yourself whether an optimization (making code faster, graphs prettier, etc.) is really needed.
