---
title: 'R: Tutorial & Command-Collection'
subtitle: '(for applications in economics)'
author: "Marko Mlikota, https://markomlikota.github.io"
output:
  html_document: 
    fig_width: 6
    fig_height: 3.75
    fig_caption: true
    highlight: zenburn
    toc: false
    toc_depth: 1
    toc_float: true
    number_sections: false
    css: style.css
  pdf_document:
    fig_width: 6
    fig_height: 3.75
    fig_caption: true
    highlight: zenburn
---


<style type="text/css">
body, td {
   font-size: 18px;
}
code.r{
  font-size: 16px;
}
pre {
  font-size: 16px
}
h1 {
  font-size: 35px;
  margin: 60px 0px 30px 0px;
}
h2 {
  font-size: 25px;
}
#TOC {
  color: black; 
}

</style>

<script>
  var height=$('#primary').height(); // Calculate primary wrapper height
  $('#secondary').height(height); // Set the height it to sidebar
</script>




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(results=TRUE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(tidy=TRUE)
knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
#knitr::opts_chunk$set(fig.width=5, fig.height=3)
```


# Functions

```{r, echo=FALSE}

rm(list = ls()) # delete everything in workspace/environment
cat("\014")	# delete everything in console     

```


```{r}

# Up to now, we used functions that are pre-programmed in R or contained in a package we load. 
# The user can of course also define own functions. For example:

fMultiplyXY = function(x,y){
	x*y
}

fMultiplyXY(3,4)


# When a function uses many arguments, it can be hard to remember the argument order. 
# In that case, it is useful to specify the argument names when calling the function, 
# because then the order becomes irrelevant:

# Both give same result:
fMultiplyXY(x=3,y=4) 
fMultiplyXY(y=4,x=3) 


# One can also specify some arguments to be optional. For example:

# Here, the third argument ("z") is optional. By default, the function takes z=2.
fMultiplyXYZ = function(x, y, z=2) { 
  x * y * z
}

fMultiplyXYZ(2, 3) # uses z=2
fMultiplyXYZ(2, 3, 2) # also uses z=2
fMultiplyXYZ(2, 3, 4) # uses z=4

```

